/*---------------------------------------------------------------------

Template Name: 	YaAdmin
Version:	 	1.0
Release Date: 	December 12, 2010

File:       	yaadmin.js
Updated:    	2010-12-12

Copyright (c) 2010 Faragly Halik - http://themeforest.net/user/lifter

-----------------------------------------------------------------------

WARNING! DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING!

---------------------------------------------------------------------*/

// Yaadmin object setup
if (!Yaadmin) var Yaadmin = {}

// setup() - Yaadmin init and setup
Yaadmin.setup = function () {
    // Open an external link in a new window
    $('a[href^="http://"]').filter(function () {
        return this.hostname && this.hostname !== location.hostname;
    }).attr('target', '_blank');
	
	// outline fix
	$("a, button, input").each(function() {
		$(this).attr("hideFocus", "true").css("outline", "none");
	});
	
	if($.browser.msie) $("body").addClass(("ie"+parseInt($.browser.version)));
	if($.browser.opera) $("a.button > span > span").css('marginRight', '25px');
	// buttons in IE and Opera
	// if($.browser.msie) $(":button.button").hover(function(){ $(this).addClass('hover'); }, function(){ $(this).removeClass('hover');});
	if($.browser.opera || ($.browser.msie && $.browser.version == 7)){
		/*$(":button.button").bind("mousedown", function(){
			$(this).addClass("active");
		}).bind("mouseup mouseout", function(){
			$(this).removeClass("active");
		});*/
	}
	
	// toggle
	$("h5.toggle").toggle(function(){
		$(this).addClass("activetoggle").next(".toggle_content").show("fast");
	},function(){
		$(this).removeClass("activetoggle").next(".toggle_content").hide("fast");
	});
	
	// messages close animation
	$(".message.closeable, .message.closeable .close").live("click", function(){
		var message = $(this).parent();
		if($(this).is(".closeable")) message = $(this);
		message.animate({opacity: 0}, 250, function(){
			$(this).slideUp(100, function(){$(this).remove()})
		});
	});
	$(".message.closeable").append($('<div/>', {'class': 'close',html: '&#215;'}));
	
	$('.areatabs > .tabs').delegate('li:not(.current)', 'click', function() {
		$(this).addClass('current').siblings().removeClass('current').parent().parent().children(".panes").children('.pane').hide().eq($(this).index()).show();
		return false;
	});
	
	/* === Tables javascripts [begin] === */
	/* optional menu in the table to each row */
	$("table td a.action").live("click", function(){
		var pos = $(this).position();
		$(this).addClass("active").next().css({top: pos.top + 24, left: pos.left}).show().find("li:last a").css("border-bottom", 0);
		return false;
	});
	$("table th a.action").live("click", function(){return false;});
	/* when you click to close the active optional menu and select box */
	$("body").click(function(event){
		$.each($("a.action.active"), function(){
			$(this).removeClass("active").next().hide();
		});
	});
	
	/* the effect of zebra */
	$("table.table tbody tr:odd").css({backgroundColor: "#fbfbfb"});
	
	/* Check all */
	$('input:checkbox.checkall').click(function() {
		$(this).parents('.table').find('input:checkbox').attr('checked', $(this).is(':checked')).parents("tr").each(function(){
			if($(this).find('input:checkbox').is(':checked')) $(this).addClass("selected");
			else $(this).removeClass("selected");
		});  
	});
	
	/* selection row with the active checkbox */
	$("table.table input:checkbox").change(function(){
		if($(this).is(':checked')) $(this).parents("tr").addClass("selected");
		else $(this).parents("tr").removeClass("selected");
	});
	/* === Tables javascripts [end] === */
}

Yaadmin.toolbarInit = function(){
	if($("#toolbar").length > 0){
		$("#toolbar header > a.arrow").css("opacity", .7).bind("mouseover", function(){
			$(this).stop().animate({ opacity: 1 }, 250);
		}).bind("mouseout", function(){
			$(this).stop().animate({ opacity: .7 }, 250);
		}).click(function(){
			if($(this).hasClass("up")){
				$(this).css("opacity", .7).bind("mouseover", function(){
					$(this).stop().animate({ opacity: 1 }, 250);
				}).bind("mouseout", function(){
					$(this).stop().animate({ opacity: .7 }, 250);
				});
				$("#toolbar").unbind("mouseover mouseout click");
				$(this).removeClass("up");
				$("#toolbar header").removeAttr("style");
				$("#toolbar .toolbar-content").show("fast");
			}else{
				$(this).unbind("mouseover mouseout");
				$("#toolbar").bind("mouseover", function(){
					$(this).stop().animate({ opacity: 1 }, 250);
				}).bind("mouseout", function(){
					$(this).stop().animate({ opacity: .7 }, 250);
				}).bind("click", function(){
					$("#toolbar header > a.arrow").click();
				});
				$("#toolbar header").attr("style", "cursor:pointer;");
				$(this).addClass("up");
				$("#toolbar .toolbar-content").hide("fast");
			}
			return false;
		});
	}
}
